export const environment = {
  production: true,
  useSQLite: false,
  databaseName: 'MNT_DB_',
  databaseVersion: 1,
  serverURL: 'https://bpa4.arribatecmarine.com/InfoSHIP_EVO_MCM_41',
  isUsingMCM: false,
  serviceUser: 'service',
  servicePassword: 'SeRvIcE_&%1234',
  serviceCompany: '001',
  loggedUser: 'a.volpino',
  loggedPassword: 'IB1234',
  loggedUserCode: '7763',
  maintenanceModuleActive: false,
  purchaseModuleActive: true,
  isDevelopmentVersion: false,
};
