export const versionUpgrades = [
  {
    toVersion: 1,
    statements: [
      `CREATE TABLE personnel(
        PERSONID varchar PRIMARY KEY NOT NULL,
        PERSONCDUNIT varchar,
        PERSONNAME varchar,
        PERSONDTSTART varchar,
        PERSONDTSTOP varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar
        );`,
      `CREATE TABLE assetLocation(
          ASLOCODE varchar PRIMARY KEY NOT NULL,
          ASLOTILELABEL1 varchar,
          ASLOTILELABEL2 varchar,
          ASLOTILELABEL3 varchar,
          ASLOTILELABEL4 varchar,
          ASLOTILELABEL5 varchar,
          ASLOTILELABEL6 varchar,
          ASLOTILELABEL7 varchar,
          ASLOTILELABEL8 varchar,
          ASLOTILELABEL9 varchar,
          ASLOISTEMPLATE varchar,
          ASLOIDPATH varchar,
          ASLOLABEIMAGE varchar,
          ASLOISSERIALNR varchar,
          ASLOIDITEM varchar,
          ASLOCDCLASS varchar,
          ASLOSERIALNR varchar,
          ASLODESCR varchar,
          ASLOCDUNIT varchar,
          ASLODOWN varchar,
          ASLOISMAINT varchar,
          ASLOISUNIQUE varchar,
          ASLODTSTART varchar,
          ASLOFAMILY varchar,
          ASLOTILEDATA1 varchar,
          ASLOTILEDATA2 varchar,
          ASLOTILEDATA3 varchar,
          ASLOTILEDATA4 varchar,
          ASLOTILEDATA5 varchar,
          ASLOTILEDATA6 varchar,
          ASLOTILEDATA7 varchar,
          ASLOTILEDATA8 varchar,
          ASLOTILEDATA9 varchar,
          ASLOCDDEPTO varchar,
          ASLOCRITICALRANK varchar,
          ASLODESCR2 varchar,
          ASLOPATHSHORTCODE varchar,
          ASLONOTE varchar,
          ASLOCDSHORT varchar,
          ASLOCOMPANYID varchar,
          ASLOTYPE varchar,
          ASLOLABECOLOR varchar,
          ASLOIDPARENT varchar,
          ASLOSTATUS varchar,
          PAR_CDUNIT varchar,
          pTop varchar,
          CANCELLED varchar,
          UPDATEDATETIME varchar,
          UPDATEOFFSET varchar,
          CUSTOMFIELD varchar,
          RECORDCOUNTER varchar
          );`,
    ],
  },
];
