export const versionUpgrades = [
  {
    toVersion: 1,
    statements: [
      `CREATE TABLE assetLocation(
        ASLOCODE varchar PRIMARY KEY NOT NULL,
        ASLOTILELABEL1 varchar,
        ASLOTILELABEL2 varchar,
        ASLOTILELABEL3 varchar,
        ASLOTILELABEL4 varchar,
        ASLOTILELABEL5 varchar,
        ASLOTILELABEL6 varchar,
        ASLOTILELABEL7 varchar,
        ASLOTILELABEL8 varchar,
        ASLOTILELABEL9 varchar,
        ASLOISTEMPLATE varchar,
        ASLOIDPATH varchar,
        ASLOLABEIMAGE varchar,
        ASLOISSERIALNR varchar,
        ASLOIDITEM varchar,
        ASLOCDCLASS varchar,
        ASLOSERIALNR varchar,
        ASLODESCR varchar,
        ASLOCDUNIT varchar,
        ASLODOWN varchar,
        ASLOISMAINT varchar,
        ASLOISUNIQUE varchar,
        ASLODTSTART varchar,
        ASLOFAMILY varchar,
        ASLOTILEDATA1 varchar,
        ASLOTILEDATA2 varchar,
        ASLOTILEDATA3 varchar,
        ASLOTILEDATA4 varchar,
        ASLOTILEDATA5 varchar,
        ASLOTILEDATA6 varchar,
        ASLOTILEDATA7 varchar,
        ASLOTILEDATA8 varchar,
        ASLOTILEDATA9 varchar,
        ASLOCDDEPTO varchar,
        ASLOCRITICALRANK varchar,
        ASLODESCR2 varchar,
        ASLOPATHSHORTCODE varchar,
        ASLONOTE varchar,
        ASLOCDSHORT varchar,
        ASLOCOMPANYID varchar,
        ASLOTYPE varchar,
        ASLOLABECOLOR varchar,
        ASLOIDPARENT varchar,
        ASLOSTATUS varchar,
        PAR_CDUNIT varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        CUSTOMFIELD varchar,
        RECORDCOUNTER varchar
        );`,
      `CREATE TABLE classification(
        CLASCODE varchar PRIMARY KEY NOT NULL,
        CLASDESCR varchar,
        CLASISASSET varchar,
        CLASPARENTID varchar,
        CLASPATH varchar,
        CLASCDUNIT varchar,
        CLASCOMPANYID varchar,
        CLASISITEM varchar,
        CLASINHERITBY varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar
        );`,
      `CREATE TABLE component(
        COGRCDCOMP varchar NOT NULL,
        COGRCDCLASS varchar NOT NULL,
        COGRCDPATH varchar,
        COGRISDEFAULT varchar,
        COGRDESCR varchar,
        COGRCDPARENT varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar,
        PRIMARY KEY (COGRCDCOMP, COGRCDCLASS)
        );`,
      `CREATE TABLE componentProblem(
        PRCOCDCOMP varchar NOT NULL,
        PRCOCDCLASS varchar NOT NULL,
        PRCOCDPROBLEM varchar NOT NULL,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar,
        PRIMARY KEY (PRCOCDCOMP, PRCOCDCLASS, PRCOCDPROBLEM)
        );`,
      `CREATE TABLE problem(
        PROBCODE varchar PRIMARY KEY NOT NULL,
        PROBDESCR varchar,
        PROBDESCR2 varchar,
        PROBCDACTIVITY varchar,
        PROBCDCATE varchar,
        PROBISSYMPTOM varchar,
        PROBISFAILMODE varchar,
        PROBCDUNIT varchar,
        PROBCOMPANYID varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar
        );`,
      `CREATE TABLE personnel(
        PERSONID varchar PRIMARY KEY NOT NULL,
        PERSONCDUNIT varchar,
        PERSONNAME varchar,
        PERSONDTSTART varchar,
        PERSONDTSTOP varchar,
        pTop varchar,
        CANCELLED varchar,
        UPDATEDATETIME varchar,
        UPDATEOFFSET varchar,
        RECORDCOUNTER varchar
        );`,
      `CREATE TABLE workRequest(
        IDLIST varchar PRIMARY KEY NOT NULL,
        WOREWRTYCODE varchar,
        WORECDUNIT varchar,
        WORESTATCODE varchar,
        WOREDESCR varchar,
        WOREDATETIME varchar,
        WOREOFFSET varchar,
        WOREPERSREPO varchar,
        WOREDTREPO varchar,
        WOREOFSREPO varchar,
        WOREASLOCODE varchar,
        WORECLASCODE varchar,
        WORECOGRCODE varchar,
        WOREPROBCODE varchar,
        WORENUMBER varchar,
        WORENOTE varchar,
        WORENRATTACH varchar,
        WOREISREPGUEST varchar,
        IDLISTDEVICE varchar,
        DEVICEID varchar,
        CREATIONUSER varchar,
        CREATIONDATETIME varchar,
        CREATIONOFFSET varchar,
        SYNC integer
        );`,
      `CREATE TABLE reqHeaders(
        IDDOC varchar PRIMARY KEY NOT NULL,
        NRDOC varchar,
        DSDOC varchar,
        DTDOC varchar,
        DSUNIT varchar,
        CDCURRENCY varchar,
        NEXTSTATUSES varchar,
        USERS varchar
        );`,
      `CREATE TABLE reqRows(
        IDDOC varchar NOT NULL,
        CPROWNUM varchar NOT NULL,
        IDITEM varchar,
        DSITEM varchar,
        QTITEM varchar,
        CDUOM varchar,
        PRIMARY KEY (IDDOC, CPROWNUM)
        );`,
    ],
  },
];
